title: RonnieNote
tagline: about Tech & Life

author:
  name: Ronnie Tsao
  url: https://www.facebook.com/profile.php?id=100011899186925&locale=zh_TW

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
